#!/bin/sh

cd "`dirname "$0"`"

OUT="3D"
LOG=$OUT.log

INCLUDES="-I./include"
LIBS="-F/Library/Frameworks \
	-framework SDL2 -framework OpenGL \
	-lGLEW -lassimp"

SRC_FILES="src/def.c src/cvar.c src/g_*.c src/v_*.c src/sys_sdl.c"

ADD_PARAMS="-Wall -std=c99"

echo `gcc -o $OUT \
	$INCLUDES $LIBS \
	$SRC_FILES $ADD_PARAMS` > $LOG
